import sqlite3

dbase = sqlite3.connect('library.db')

print('Database is opened')

"""dbase.execute(''' CREATE TABLE bookctg(
BOOKCATEGORYID INT PRIMARY KEY NOT NULL,
CATEGORYNAME TEXT NOT NULL)''')

dbase.execute(''' CREATE TABLE books(
BOOKID INT PRIMARY KEY NOT NULL,
BOOKNAME TEXT NOT NULL,
BOOKAUTHOR TEXT NOT NULL,
BOOKPUBLISHER TEXT NOT NULL,
BOOKPAGE INT NOT NULL,
BOOKCATEGORYID INT  NOT NULL,
FOREIGN KEY(BOOKCATEGORYID) REFERENCES bookctg(BOOKCATEGORYID))''')


dbase.execute(''' CREATE TABLE user(
USERID INT PRIMARY KEY NOT NULL,
USERNAME TEXT NOT NULL,
USERSURNAME TEXT NOT NULL,
PHONENUMBER CHAR(11) NOT NULL,
USERLOGINNAME VARCHAR(15) NOT NULL,
PASSWORD INT NOT NULL)''')


dbase.execute(''' CREATE TABLE admin(
ADMINID INT PRIMARY KEY NOT NULL,
ADMINUSERNAME VARCHAR(15) NOT NULL,
ADMINPASS INT NOT NULL)  
''')


dbase.execute(''' CREATE TABLE issuereturn(
ISSUEID INT PRIMARY KEY NOT NULL,
USERID INT NOT NULL,
BOOKID INT NOT NULL,
ISSUEDATE DATETIME NOT NULL,
RETURNDATE DATETIME NOT NULL,
BORROW INT NOT NULL,
FOREIGN KEY(USERID) REFERENCES user(USERID),
FOREIGN KEY(BOOKID) REFERENCES books(BOOKID))
''')




dbase.execute(''' INSERT INTO user VALUES(?,?,?,?,?,?)''',('1','Elif','Yilmaz', '05340330927','elifyilmaz','123456'))
dbase.commit()
"""

dbase.execute(""" INSERT INTO admin VALUES(?,?,?)""", ('1','elif','12305'))
dbase.commit()

dbase.close()